-- Add missing columns required by startup routines (non-destructive)
ALTER TABLE trade_simulations
  ADD COLUMN IF NOT EXISTS simulation_type TEXT,
  ADD COLUMN IF NOT EXISTS confidence REAL,
  ADD COLUMN IF NOT EXISTS profitLikelihood REAL,
  ADD COLUMN IF NOT EXISTS entryPrice NUMERIC,
  ADD COLUMN IF NOT EXISTS tpPrice NUMERIC,
  ADD COLUMN IF NOT EXISTS slPrice NUMERIC,
  ADD COLUMN IF NOT EXISTS amount NUMERIC,
  ADD COLUMN IF NOT EXISTS startTime TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS endTime TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS profitablePercentage REAL,
  ADD COLUMN IF NOT EXISTS highestProfit NUMERIC,
  ADD COLUMN IF NOT EXISTS lowestLoss NUMERIC,
  ADD COLUMN IF NOT EXISTS successScore REAL,
  ADD COLUMN IF NOT EXISTS successScoreThreshold REAL,
  ADD COLUMN IF NOT EXISTS isSuccessful BOOLEAN,
  ADD COLUMN IF NOT EXISTS timeInProfitRatio REAL,
  ADD COLUMN IF NOT EXISTS maxFavorableExcursion NUMERIC,
  ADD COLUMN IF NOT EXISTS maxDrawdown NUMERIC,
  ADD COLUMN IF NOT EXISTS durationMinutes INTEGER,
  ADD COLUMN IF NOT EXISTS finalProfitableSeconds INTEGER,
  ADD COLUMN IF NOT EXISTS marketConditions JSONB,
  ADD COLUMN IF NOT EXISTS indicatorValues JSONB,
  ADD COLUMN IF NOT EXISTS completionProcessed BOOLEAN,
  ADD COLUMN IF NOT EXISTS lastProcessedAt TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS processVersion INTEGER,
  ADD COLUMN IF NOT EXISTS currentProfitPercent NUMERIC,
  ADD COLUMN IF NOT EXISTS profitTime INTEGER,
  ADD COLUMN IF NOT EXISTS lossTime INTEGER,
  ADD COLUMN IF NOT EXISTS lastUpdateTimestamp TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS actualMovementPercent NUMERIC,
  ADD COLUMN IF NOT EXISTS maxPriceDuringTrade NUMERIC,
  ADD COLUMN IF NOT EXISTS minPriceDuringTrade NUMERIC,
  ADD COLUMN IF NOT EXISTS excludedFromLearning BOOLEAN,
  ADD COLUMN IF NOT EXISTS movementFilterThreshold NUMERIC,
  ADD COLUMN IF NOT EXISTS avgForecastAccuracy REAL,
  ADD COLUMN IF NOT EXISTS earlyAccuracy3min REAL,
  ADD COLUMN IF NOT EXISTS volatilityAlignmentScore REAL,
  ADD COLUMN IF NOT EXISTS driftCorrectionApplied BOOLEAN,
  ADD COLUMN IF NOT EXISTS completedAt TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updatedAt TIMESTAMPTZ;

ALTER TABLE rolling_chart_data
  ADD COLUMN IF NOT EXISTS rsi REAL,
  ADD COLUMN IF NOT EXISTS macd REAL,
  ADD COLUMN IF NOT EXISTS macd_signal REAL,
  ADD COLUMN IF NOT EXISTS macd_histogram REAL,
  ADD COLUMN IF NOT EXISTS bollinger_upper NUMERIC,
  ADD COLUMN IF NOT EXISTS bollinger_lower NUMERIC,
  ADD COLUMN IF NOT EXISTS stochastic REAL,
  ADD COLUMN IF NOT EXISTS fundingRate NUMERIC,
  ADD COLUMN IF NOT EXISTS nextFundingTime TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS openInterest NUMERIC,
  ADD COLUMN IF NOT EXISTS openInterestChange NUMERIC,
  ADD COLUMN IF NOT EXISTS tradeCount INTEGER,
  ADD COLUMN IF NOT EXISTS buyVolume NUMERIC,
  ADD COLUMN IF NOT EXISTS sellVolume NUMERIC,
  ADD COLUMN IF NOT EXISTS avgTradeSize NUMERIC,
  ADD COLUMN IF NOT EXISTS largestTrade NUMERIC;

ALTER TABLE learning_weights
  ADD COLUMN IF NOT EXISTS indicator_name TEXT;

ALTER TABLE ml_prediction_history
  ADD COLUMN IF NOT EXISTS confidence REAL;

