name: CI
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json
      - name: Install deps
        working-directory: client
        run: npm ci
      - name: Type-check & build
        working-directory: client
        run: |
          npm run build
      - name: ASCII scan (fail on smart quotes/dashes etc.)
        run: |
          set -e
          # list of text extensions to scan
          exts='ts tsx js jsx css html md json yml yaml ps1 ps2'
          # find text files and grep for non-ASCII (tab, LF, CR, space..~)
          files=$(git ls-files | grep -E "\.($(echo $exts | sed 's/ /|/g'))$" || true)
          if [ -n "$files" ]; then
            bad=$(echo "$files" | xargs -r grep -nI -P '[^\x09\x0A\x0D\x20-\x7E]' || true)
            if [ -n "$bad" ]; then
              echo "::error title=Non-ASCII characters detected::"
              echo "$bad"
              exit 1
            fi
          fi
      - name: Prevent accidental Windows CRLF
        run: |
          if git ls-files | xargs -r file | grep -E ':.* CRLF' -n; then
            echo "::warning title=CRLF detected::Convert to LF to avoid diff noise"
          fi
